### ISSUE TITLE
add helper function for plugin exception handling (pytest_inmanta.raises)

### ISSUE THREAD

**Issue by sanderr** [inmanta/pytest-inmanta#127]
`pytest.raises` does not work for custom `ExplicitPluginException` because of the dynamism described in the `pytest-inmanta` README. The exception class would be evaluated before the compile so the exception that gets raised is not an instance of that class. `examples/testmodule/tests/test_import.py::test_inmanta_plugins_except` shows how such an exception can be handled using the `inmanta_plugins` fixture. This approach is not very intuitive. A helper function similar to `pytest.raises` could be added to `pytest-inmanta`. The function should return an object that supports the context management protocol so that it's use is as close as possible to `pytest.raises`. It will probably be required to add an `InmantaPluginsImportLoader` argument.

**Comment by bartv** [comment]
I think this is now fixed with modules v2 and we can close this issue. If not, please reopen it.
