### ISSUE TITLE
support plugin code with side effects (i.e. module-level cache)

### ISSUE THREAD

**Issue by sanderr** [inmanta/pytest-inmanta#248]
The recent changes to pytest-inmanta's module loading (#245) don't play well with side effects on module objects that should be contained to a compile. After discussion the proposed solution is to add support for one or more cleanup hook functions on any module's Python module (`inmanta_plugins` submodules of any depth), identified by name. For now these cleanup functions would be used by pytest-inmanta before each compile (keep state after compile so it can be investigated from test cases).

# Affected modules
The following modules should be fixed after adding support to pytest-inmanta
- [x] std
- [x] lsm
- [x] terraform
- [x] connect
- [x] bics_ce

**Comment by wouterdb** [comment]
I don't know if we need to support 'any depth' but I guess it doesn't matter a lot in the implementation

**Comment by sanderr** [comment]
Indeed. I initially wrote that it should be on the top-level module but then I realized that it wouldn't simplify implementation and it does take away a bit of flexibility so I changed it.

**Comment by arnaudsjs** [comment]
This issue also exists on the `std` module, since it has several cache fields: `fact_cache`, `tcache` and `engine_cache`.

**Comment by bartv** [comment]
I created PR on std and lsm to use an older version. When this issue is resolved we need to implement it on std and lsm and remove the constraint.

**Comment by sanderr** [comment]
Reopening because the affected modules still need fixing.
