### ISSUE TITLE
Add support for creating the project is a non-temporary directory

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/pytest-inmanta#393]
**Problem description:**

`pytest-inmanta` creates an Inmanta project to run the tests against. This project is created in a temporary directory, by the `project_dir` fixture. This fixture cleans up the project when the test run finishes. This means that if something goes wrong, there is no way to inspect:

* What the project.yml of the project looks like.
* What the content of the venv of the project looks like.

Both are really useful to debug issues.

**Proposal:**

Add a configuration option to indicate that the project should be created in a specific directory instead of a temporary directory. That directory should not be cleaned up when the test suite finishes.

**Comment by sanderr** [comment]
Or even just with `--pdb`

**Comment by sanderr** [comment]
Discussed in planning meeting. Closing in favor of `--pdb`
