### ISSUE TITLE
get_plugin and import inmanta_plugins produce inconsistent results

### ISSUE THREAD

**Issue by wouterdb** [inmanta/pytest-inmanta#49]
# Problem

The code loading by `get_plugin`  and `import inmanta_plugins` is considered different.

related to #46 

# Example

```python
class TestException(Exception):
   pass

@plugin
get_exception():
   return TestException
```

```python
def test_plugin(project):
   from  inmanta_plugins.unittest get TestException
   testexception = project.get_plugin("get_exception)()
   assert TestException == testexception
```

This will fail with 

```
AssertionError: assert <class 'inmanta_plugins.unittest.__init__.TestException'> == <class 'inmanta_plugins.unittest.TestException'>
```

observe that the plugin loads the code in the wrong package: it has the filename in it, even if it is `__init__`

# Notes

There could be more subtle problems when doing a compile, as it may re-load the code:

What could be tested

```python
def test_plugin(project):
   from  inmanta_plugins.unittest import get TestException
   testexception = project.get_plugin("get_exception)()
   assert TestException is testexception
   
   project.compile("import unittest")

   from  inmanta_plugins.unittest import get TestException
   assert TestException is testexception
   testexception2 = project.get_plugin("get_exception)()
   assert TestException is testexception2
   assert testexception is testexception2

```

**Comment by sanderr** [comment]
An additional issue occurs when loading `plugins/__init__.py` has side effects. It is loaded multiple times so the side effects are also executed multiple times. For example:

`plugins/__init__.py`:
```
print("loading")
```

`tests/test_side_effects.py`:
```
def test_side_effects(project):
    # not sure how to actually test this but it prints "loading" three times
    assert False
```

As far as I know the loading is executed at three places:
1. the loading by the compiler
2. loading with `imp` in `_load_plugins`. This could probably be resolved by using `importlib` instead.
3. loading all `*.py` files in the plugins dir. This reloads `__init__.py` as well.

**Comment by wouterdb** [comment]
see also #46
